Repository Azure/BatchExplorer, pull requests merged in 2018-03, with the labels that each got.

#1134 Fix: osx build
  .travis.yml
  app/components/file/details/log-file-viewer/log-file-viewer.component.ts
  package.json
  yarn.lock
Labels: internal

#1166 Remove ssh/rdp ports from reserved backend ports
  app/components/pool/network-configuration/pool-endpoint-helper.ts
Labels: bug

#1221 Feature: New select component
  app/components/account/home/account-home.html
  app/components/data/home/data-home.html
  src/@batch-flask/ui/batchui.module.ts
  src/@batch-flask/ui/browse-layout/browse-layout.scss
  src/@batch-flask/ui/index.ts
  src/@batch-flask/ui/select/index.ts
  src/@batch-flask/ui/select/option/index.ts
  src/@batch-flask/ui/select/option/option.component.ts
  src/@batch-flask/ui/select/option/option.html
  src/@batch-flask/ui/select/option/option.scss
  src/@batch-flask/ui/select/select.component.spec.ts
  src/@batch-flask/ui/select/select.component.ts
  src/@batch-flask/ui/select/select.html
  src/@batch-flask/ui/select/select.module.ts
  src/@batch-flask/ui/select/select.scss
Labels: work in progress
